version: "3.8"
services:
  postgres_db:
    container_name: "postgres_db"
    image: "postgres"
    env_file: ./.env
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:${DB_VOLUME_URL}

  chroma_db:
    container_name: "chroma_db"
    image: "ghcr.io/chroma-core/chroma:0.5.4"
    ports:
      - ${CHROMA_LOCAL_PORT}:${CHROMA_DOCKER_PORT}
volumes:
  postgres_data: